### PR TITLE
Close #1281 Billing invoice not create bug

### LINKED ISSUE #1281: Billing invoice not create bug

### PR DESCRIPTION
**Pull request by Regene27**
image

### CODE REVIEW

File: app/models/spree_cm_commissioner/variant_decorator.rb [hunk 1]
```diff
@@ -27,8 +27,9 @@ def selected_option_value_ids
 
     def display_variant
       display_sku = sku.split('-').join(' ')
-      display_price = price.to_i == price ? price.to_i : price
-      "#{display_sku} - #{display_price} ៛"
+      price.to_i == price ? price.to_i : price
```
Comment (channainfo) [inline app/models/spree_cm_commissioner/variant_decorator.rb:30]: This line appears to have no effect. let's add some tests to clarify its intended purpose?

File: app/views/spree/billing/shared/_invoice.html.erb [hunk 2]
```diff
@@ -26,6 +26,11 @@
   @invoice_number = @invoice.invoice_number
   @customer_number = @customer.customer_number
   @customer_address = @order.billing_address&.address1
+  if @current_vendor.payment_qrcode.present?
+    @qrcode = "<img src=\"#{main_app.rails_blob_url(@current_vendor.payment_qrcode.attachment)}\" alt=\"qrcode\" style=\"width: 150px;\">".html_safe
```
Comment (channainfo) [inline app/views/spree/billing/shared/_invoice.html.erb:30]: use a helper instead.

**Review by channainfo — CHANGES_REQUESTED** [review]
