### PR TITLE
Close #1790 fix error with background image upload in guest card classes page

### LINKED ISSUE #1790: Fix error with background image upload in GuestCardClasses page
pic1

### PR DESCRIPTION
**Pull request by Sreyleak-Deth**
### Before:

pic1

### After:
image

### CODE REVIEW

File: app/controllers/spree/admin/guest_card_classes_controller.rb [hunk 1]
```diff
@@ -52,10 +60,13 @@ def location_after_save
 
       # override
       # permit all attributes for now.
+
       def permitted_resource_params
-        key = ActiveModel::Naming.param_key(@object)
-        permit_keys = params.require(key).keys
-        params.require(key).permit(permit_keys)
+        @permitted_resource_params ||= begin
+          key = ActiveModel::Naming.param_key(@object)
```
Comment (channainfo) [inline app/controllers/spree/admin/guest_card_classes_controller.rb:66]: Let's permit the params keys explicitly one by one here.

**Review by channainfo — CHANGES_REQUESTED** [review]

File: app/controllers/spree/admin/guest_card_classes_controller.rb (hunk 1 above)
Comment (Sreyleak-Deth) [reply app/controllers/spree/admin/guest_card_classes_controller.rb:66]: > Let's permit the params keys explicitly one by one here.

Got it bong, I will update it, Thanks
