### PR TITLE
close #793 fix undefine method user.full_name empty? for nil:nilClass

### LINKED ISSUE #793: user.full_name undefined method `empty?' for nil:NilClass

### PR DESCRIPTION
**Pull request by theachoem**
```
Application spree_starter


⚠️ Error occurred in production ⚠️
An *ActionView::Template::Error* occurred in *payments#show*.


Exception:
undefined method `empty?' for nil:NilClass


Set by controller:
{:user=>"36"}


Request:
'''
* url : https://api-production.bookme.plus/admin/orders/R217413959/payments/PYN5QOHJ
* http_method : GET
* ip_address : 43.230.192.190
* parameters : {"controller"=>"spree/admin/payments", "action"=>"show", "order_id"=>"R217413959", "id"=>"PYN5QOHJ"}
* timestamp : 2023-11-07 14:13:31 +0700
'''

Backtrace:
'''
* /app/vendor/bundle/ruby/3.2.0/bundler/gems/commissioner-f7fd54246a52/app/models/spree_cm_commissioner/user_decorator.rb:32:in `reject'
* /app/vendor/bundle/ruby/3.2.0/bundler/gems/commissioner-f7fd54246a52/app/models/spree_cm_commissioner/user_decorator.rb:32:in `full_name'
* /app/vendor/bundle/ruby/3.2.0/bundler/gems/spree_vpago-6df6b9e923f7/app/views/spree/admin/payments/source_views/_vpago_payment_tmpl.html.erb:52:in `_vendor_bundle_ruby_______bundler_gems_spree_vpago__df_b_e___f__app_views_spree_admin_payments_source_views__vpago_payment_tmpl_html_erb__705148606067906546_717380'
* /app/vendor/bundle/ruby/3.2.0/gems/actionview-7.0.8/lib/action_view/base.rb:244:in `public_send'
* /app/vendor/bundle/ruby/3.2.0/gems/actionview-7.0.8/lib/action_view/base.rb:244:in `_run'
'''
```

### CODE REVIEW

File: app/models/spree_cm_commissioner/user_decorator.rb [hunk 1]
```diff
@@ -29,7 +29,7 @@ def normal_user?
     end
 
     def full_name
-      [first_name, last_name].reject(&:empty?).join(' ')
+      [first_name, last_name].reject { |name| name&.strip.blank? }.join(' ').presence
```
Comment (channainfo) [inline app/models/spree_cm_commissioner/user_decorator.rb:32]: Maybe 
```
[first_name, last_name].compact_blank.join(' ') 
```
is more readable.

**Review by channainfo — CHANGES_REQUESTED** [review]
