### PR TITLE
close #1975 Fix kyc resource not found

### LINKED ISSUE #1975: Fix Kyc resource not found

### PR DESCRIPTION
**Pull request by SreyMochOrng**
### Fix error on kyc struggling on loading when editing 

image

### CODE REVIEW

File: app/controllers/spree/api/v2/storefront/guests_controller.rb [hunk 1]
```diff
@@ -13,17 +13,6 @@ def collection
             model_class.all
           end
 
-          # show by guest token
-          def show
-            guest = model_class.find_by(token: params[:id])
```
Comment (channainfo) [inline app/controllers/spree/api/v2/storefront/guests_controller.rb:18]: Are we using this API to query the guest in the HM ticket system? Another solution for compatibility could be checking the length of params[:id] to determine whether to search by ID or token.

**Review by channainfo — CHANGES_REQUESTED** [review]
