### PR TITLE
Close #1711 Billing report overview bug

### LINKED ISSUE #1711: billing report overview bug
In overview overdue tab, orders query has duplication

### PR DESCRIPTION
**Pull request by Regene27**
- fixed duplication bug in report overview
- fixed duplication bug in overdue page
- fixed duplication bug in failed_order page

How the bug happen:
- When one order has two or more line_items(subscription), the query get the same order multiple times(same number as line_items)

To reproduce bug:
- Subscribe to multiple products in one order

How to fix:
- As the order_id shown multiple times is the same, let the query select unique order_id

### CODE REVIEW

**Comment by channainfo** [comment]
@Regene27 describe the following in the description:
- how  to bug happen
- steps to reproduce it
- how you fix it.

File: app/controllers/spree/billing/reports_controller.rb [hunk 1]
```diff
@@ -37,13 +37,16 @@ def balance_due
...
                               .where('spree_line_items.due_date < ?', Time.zone.today)
+                              .select('DISTINCT ON (spree_orders.id) spree_orders.*, spree_line_items.*')
                               .ransack(params[:q])
         @orders = @search.result.page(page).per(per_page)
       end
 
       # GET /billing/reports/failed_orders
       def failed_orders
-        @search = orders_scope.joins(:line_items).where(payment_state: 'failed').ransack(params[:q])
+        @search = orders_scope.joins(:line_items).where(payment_state: 'failed')
```
Comment (channainfo) [inline app/controllers/spree/billing/reports_controller.rb:47]: Add some rspec test to prove the issue is correctly done.

**Review by channainfo — CHANGES_REQUESTED** [review]
