### PR TITLE
close #764 fixed nearby-place error

### LINKED ISSUE #764: Nearby place error
Application spree_starter

⚠️ Error occurred in production ⚠️
A *NoMethodError* occurred in *nearby_places#new*.

Exception:
undefined method `[]' for nil:NilClass

Set by controller:
{:user=>"2"}

Request:
```
* url : https://api-production.bookme.plus/admin/vendors/summer-resort-kep/nearby_places/new?name=crab
* http_method : GET
* ip_address : 43.230.192.190
* parameters : {"name"=>"crab", "controller"=>"spree/admin/nearby_places", "action"=>"new", "vendor_id"=>"summer-resort-kep"}
* timestamp : 2023-10-30 15:53:34 +0700
```

Backtrace:
```
* /app/vendor/bundle/ruby/3.2.0/bundler/gems/commissioner-29a202c3406c/app/interactors/spree_cm_commissioner/vendor_nearby_place_builder.rb:14:in `block in call'
* /app/vendor/bundle/ruby/3.2.0/bundler/gems/commissioner-29a202c3406c/app/interactors/spree_cm_commissioner/vendor_nearby_place_builder.rb:9:in `each'
* /app/vendor/bundle/ruby/3.2.0/bundler/gems/commissioner-29a202c3406c/app/interactors/spree_cm_commissioner/vendor_nearby_place_builder.rb:9:in `each_with_index'
* /app/vendor/bundle/ruby/3.2.0/bundler/gems/commissioner-29a202c3406c/app/interactors/spree_cm_commissioner/vendor_nearby_place_builder.rb:9:in `call'
* /app/vendor/bundle/ruby/3.2.0/gems/interactor-3.1.2/lib/interactor.rb:143:in `block in run!'
```

### PR DESCRIPTION
**Pull request by tykeaboyloy**
image
image
-problem: Some places doesn't contain "types" attribute.

### CODE REVIEW

File: app/interactors/spree_cm_commissioner/vendor_nearby_place_builder.rb [hunk 1]
```diff
@@ -8,10 +8,9 @@ def call
       json_response = fetch_nearby_places
       json_response['results'].each_with_index do |json, _|
         place = SpreeCmCommissioner::Place.find_or_initialize_by(reference: json['reference'])
-
         place.assign_attributes(
           reference: json['reference'],
-          types: json['types'][0],
+          types: json['types'].nil? ? '' : json['types'][0],
```
Comment (channainfo) [inline app/interactors/spree_cm_commissioner/vendor_nearby_place_builder.rb:13]: @tykeaboyloy use json['types'].blank? instead coz nil and [ ] are blank.

If json['types'] is an empty array, it will fail again with json['types'][0]

**Review by channainfo — CHANGES_REQUESTED** [review]
